# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:36
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('80.00'), max_digits=10, null=True),
        ),
    ]
