# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 20:19
from __future__ import unicode_literals

from django.db import migrations
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170520_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=product.models.IntegerRangeField(blank=True, null=True),
        ),
    ]
