# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170514_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=shop.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, upload_to=shop.models.content_file_name),
        ),
    ]
